### ISSUE TITLE
Missing Default Icons/Models

### ISSUE THREAD

**Issue by Zinal001** [StrangeLoopGames/EcoModKit#1]
So, I just downloaded this Unity Package and was following along the tutorial [here](https://github.com/StrangeLoopGames/EcoModKit/wiki/Items-&-World-Objects) when I realized that the Package no longer contains any prefabs/models/icons, the Items folder is basically empty (except for the empty sub-folders).

Is this intentional? Would be great to have something to start with and not just start from scratch.

**Comment by nfullersl** [comment]
Ah, yeah I think I included the blank package.  I'll re upload a new one
later.  Everything should still function though.

**Comment by Zinal001** [comment]
Everything functions correctly but it would be nice to have an item/block in the package as a reference. (I've made several blocks that were WAY to big =P)

**Comment by metachronism** [comment]
closing this out, modkit undergoing major upgrade
