### ISSUE TITLE
Update for 0.8.2, automate release

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoModKit#10]

**Comment by Ferchibald** [comment]
Just an update from the comment I left on discord:
Reversing to Unity version 2018.2.0f2 worked to create worldobjects and items, but: 
- Avatar parts(tools can be equipped and work but the model is invisible).
- BlockSets(blocks can be placed but become invisible and noncollidable upon placement).

**Comment by Ferchibald** [comment]
Another update: 
Blocksets work, but unable to make them turnable blocks (like stairs)

**Comment by haykazkotanjyanslg** [comment]
This is for modkit
