### ISSUE TITLE
Mod dependencies for Mod.io

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoModKit#21]
We need mod dependencies as currently mods redistribute a version of EM Framework to make sure the mod will work out of the box, but if several mods ship the framework, in several versions, stuff breaks.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoModKit/issues/22

**Comment by TheKye** [comment]
Duplicate of #22 please close :P
