### ISSUE TITLE
Add a Setter to the Default Max Stack Size

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoModKit#23]
**Is your feature request related to a problem? Please describe.**
With our mod we provide an in house solution for altering the stack sizes for any item with a max stack size attribute, however we cant alter the original default max stack size on runtime due to not having a setter, 

**Describe the solution you'd like**
Add a setter to the Default Max stack size to allow us to override it in code  to provide a complete tool for easy stack size management without the need for the max stack size to be added to all the files

**Describe alternatives you've considered**
3rd party tools, but this requires constant updating and potential issues

**Additional context**
please?

**Comment by WeaselDog** [comment]
This will be added in 9.5 Thanks for your suggestion
