### ISSUE TITLE
Cannot decompress the package...

### ISSUE THREAD

**Issue by LinusOssmann** [StrangeLoopGames/EcoModKit#3]
I dont know why but when I try to add one of the three packages in Unity 2017.4.0f1 I'll get an failure feedback wich says that Unity was unable to decompress the package.... I hoped to find out how I can make Mods for ECO because I did'nt find good Instructions for that...

**Comment by cmgjones** [comment]
This is a git hub issue i encountered the other day , To resolve the issue download the windows git hub application and clone the rep through it . Download Git hub desktop >Clone from url
