### ISSUE TITLE
Unable to set header image for new professions

### ISSUE THREAD

**Issue by jlai** [StrangeLoopGames/EcoModKit#38]
**Is your feature request related to a problem? Please describe.**

Currently, while it's possible to add a new profession, the header image doesn't seem to show up. For example, in this screenshot:

![profession-wrongicon](https://user-images.githubusercontent.com/1415115/153334961-19177738-2271-47e0-90de-b478f9a33159.jpg)

if you click on the profession, the header image shows the image from the *last* profession tab that you clicked on, in this case the Chef profession. Per discussions on the Discord, this is supposed to be set via the "Extended Image" object on the Icon for the profession skill. However, it looks like if you try to set this via the modkit, Eco does not recognize the image.

**Describe the solution you'd like**

My theory is that this could be solved by adding the missing script used for the "Item Template" prefab which is not currently included in the modkit. As a plus, it would get rid of the error trying to use that prefab. (Side note: it would also be nice to have prefabs for common things like Skills and custom images and such)

**Describe alternatives you've considered**

Not sure how Eco handles the icons, but it seems to find the Foreground/Background/Tool images despite the missing script, so maybe the fix could be in the game instead of the modkit.

**Comment by serpopov** [comment]
added here for 9.5: https://github.com/StrangeLoopGames/Eco/pull/10491
you will need to add ExtendedImage (117x199px)
![image](https://user-images.githubusercontent.com/4238643/160653170-52166983-5b2b-4ac3-9e32-856584ba99c4.png)
