### ISSUE TITLE
Is the ModKit still updated?

### ISSUE THREAD

**Issue by AlmightyScientist** [StrangeLoopGames/EcoModKit#4]
I'm interested in modding Eco.
Is this ModKit up-to-date (and maintained), though ?

**Comment by Ubivis** [comment]
Codebranch states, that the ModKit was last updated a month ago for Version 0.7.3

**Comment by AlmightyScientist** [comment]
Yeah, sorry my question wasn't clear enough, it was more like : Do they really improve it, or is it just keept up-to-date ?

**Comment by redwyre** [comment]
Hopefully soon
